name: Deploy Storybook

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install Node Modules
        run: npm i
      - name: Build
        run: npm run build-storybook build-components
      - name: Upload Storybook to GitHub Pages
        env:
          CI: true
        run: |
          git config --global user.name "GH Pages Bot"
          git config --global user.email "bot@elementor.com"
          npm run deploy