name: Deploy Storybook

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install Node Modules
        run: npm i
      - name: Show Info
        run: git remote -v
      - name: Build
        run: npm run build-storybook build-components
      - name: Set User
        run: |
            git config --global user.name "rotemee"
            git config --global user.email "rotemee@elementor.com"
      - name: Upload Storybook to GitHub Pages
        env:
          CI: true
        run: npm run deploy