name: Deploy Storybook

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Storyboard for GitHub Pages
        env:
          CI: true
        run: |
          npm run deploy