name: Deploy Storybook

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install Node Modules
        run: npm i
      - name: Build Storybook
        run: npm run build-storybook build-components
      - name: Build Storybook2
          run: npm run build-storybook build-components
      - name: Deploy Locally
        run: npm run deploy-storybook -- --dry-run -o ./out
      - name: Upload Storybook to GitHub Pages
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd ./out
          git init
          git config user.name "GH Pages Bot"
          git config user.email "bot@elementor.com"
          git config commit.gpgsign false
          git add .
          git commit -m "Deploy Storybook to GitHub Pages"
          git push --force --quiet "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" master:gh-pages